const countriesDepthOfCoverage = {
    "fr": { name: "France", depthOfCoverage: 2, api: 1 },
    "be": { name: "Belgique", depthOfCoverage: 1, api: 1 },
    "lu": { name: "Luxembourg", depthOfCoverage: 1, api: 1 },
    "ch": { name: "Suisse", depthOfCoverage: 1, api: 1 },
    "mc": { name: "Monaco", depthOfCoverage: 1, api: 1 },
    "ma": { name: "Maroc", depthOfCoverage: 1, api: 2 },
    "ca": { name: "Canada", depthOfCoverage: 1, api: 2 },
};

const phones = {
    "original": "+33 1 73 03 73 24",
    "nord-ouest": "02 72 05 12 68",
    "nord-est": "03 72 27 20 04",
    "ile-de-france": "01 73 12 01 12",
    "sud-ouest": "05 32 00 23 05",
    "sud-est": "04 88 92 71 81",
};

const praticiens = {
    "cabinet_sarahnacass": { calendar: 7148839 },
    "cabinet_sarahnacass_2": { calendar: 8698189 },
    "residentiel_sarahnacass": { calendar: 5451421 },
};

const tarifs = {
    "union-europeenne": { value: 59400, currency: "eur", symbol: "€" },
    "canada": { value: 89000, currency: "cad", symbol: "$CAD" },
    "maroc": { value: 89000, currency: "cad", symbol: "$CAD" },
};

const locations = [
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Cergy)",
        city: "Cergy",
        address: "4-6 Rue des Chauffours, 95000 Cergy",
        acuityAddress: "4-6 Rue des Chauffours, 95000 Cergy. ",
        latitude: 49.04061738655477,
        longitude: 2.077161601787539,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Île-de-France",
        path: "/fr/sarahnacass/ile-de-france",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["cergy", "95", "val-d-oise", "ile-de-france", "paris", "idf"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["ile-de-france"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0001",
    },
    {
        pathId: 1, name: "Cabinet Sarah Nacass (Levallois-Perret)",
        city: "Levallois-Perret",
        address: "20-22 Rue Marius Aufan, 92300 Levallois-Perret",
        acuityAddress: "20-22 Rue Marius Aufan, 92300 Levallois-Perret. ",
        latitude: 48.88864725088987,
        longitude: 2.2866921784686864,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Île-de-France",
        path: "/fr/sarahnacass/ile-de-france",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["levallois-perret", "92", "hauts-de-seine", "ile-de-france", "paris", "idf"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["ile-de-france"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0002",
    },
    {
        pathId: 2, name: "Cabinet Sarah Nacass (Neuilly-sur-Seine)",
        city: "Neuilly-sur-Seine",
        address: "80 Avenue Charles de Gaulle 92200 Neuilly-sur-Seine",
        acuityAddress: "80 Avenue Charles de Gaulle 92200 Neuilly-sur-Seine. ",
        latitude: 48.88176869470149,
        longitude: 2.2711557380377947,
        accessMethods: "Métro - Les Sablons (ligne 1) / RER - Neuilly Porte Maillot - Palais Des Congrès (ligne C) / RER - Porte Maillot (ligne C)",
        parkingAccess: "74 Avenue Charles de Gaulle, Neuilly-sur-Seine",
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Île-de-France",
        path: "/fr/sarahnacass/ile-de-france",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["neuilly-sur-seine", "92", "hauts-de-seine", "ile-de-france", "paris", "idf"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["ile-de-france"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0003",
    },
    {
        pathId: 3, name: "Cabinet Sarah Nacass (Opéra)",
        city: "Opéra",
        address: "7 Rue Meyerbeer, 75009 Paris",
        acuityAddress: "7 Rue Meyerbeer, 75009 Paris. ",
        latitude: 48.87184837607562,
        longitude: 2.3331382839852512,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Île-de-France",
        path: "/fr/sarahnacass/ile-de-france",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["opera", "75", "paris-9", "ile-de-france", "paris", "idf"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["ile-de-france"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0004",
    },
    {
        pathId: 4, name: "Cabinet Sarah Nacass (Paris 2)",
        city: "Paris 2",
        address: "9 Rue du 4 Septembre, 75002 Paris",
        acuityAddress: "9 Rue du 4 Septembre, 75002 Paris. ",
        latitude: 48.86921663320713,
        longitude: 2.337758981511716,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Île-de-France",
        path: "/fr/sarahnacass/ile-de-france",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["paris", "75", "paris-2", "ile-de-france", "paris", "idf"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["ile-de-france"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0005",
    },
    {
        pathId: 5, name: "Cabinet Sarah Nacass (Paris 11)",
        city: "Paris 11",
        address: "64 Avenue Parmentier, 75011 Paris",
        acuityAddress: "64 Avenue Parmentier, 75011 Paris. ",
        latitude: 48.86302204170257,
        longitude: 2.3763788618835466,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Île-de-France",
        path: "/fr/sarahnacass/ile-de-france",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["paris", "75", "paris-11", "ile-de-france", "paris", "idf"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["ile-de-france"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0006",
    },
    {
        pathId: 6, name: "Cabinet Sarah Nacass (Paris 12)",
        city: "Paris 12",
        address: "37-39 Avenue Ledru Rollin, 75012 Paris",
        acuityAddress: "37-39 Avenue Ledru Rollin, 75012 Paris. ",
        latitude: 48.84772903116935,
        longitude: 2.3705294925669746,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Île-de-France",
        path: "/fr/sarahnacass/ile-de-france",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["paris", "75", "paris-12", "ile-de-france", "paris", "idf"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["ile-de-france"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0007",
    },
    {
        pathId: 7, name: "Cabinet Sarah Nacass (Paris 19)",
        city: "Paris 19",
        address: "11 Rue de Cambrai, 75019 Paris",
        acuityAddress: "11 Rue de Cambrai, 75019 Paris. ",
        latitude: 48.89687453781955,
        longitude: 2.3790292317795454,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Île-de-France",
        path: "/fr/sarahnacass/ile-de-france",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["paris", "75", "paris-19", "ile-de-france", "paris", "idf"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["ile-de-france"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0008",
    },
    {
        pathId: 8, name: "Cabinet Sarah Nacass (Paris République)",
        city: "Paris République",
        address: "3 bis Rue Taylor, 75010 Paris",
        acuityAddress: "3 bis Rue Taylor, 75010 Paris. ",
        latitude: 48.86943477417087,
        longitude: 2.3589610888950943,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Île-de-France",
        path: "/fr/sarahnacass/ile-de-france",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["republique", "75", "paris-10", "ile-de-france", "paris", "idf"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["ile-de-france"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0009",
    },
    {
        pathId: 9, name: "Cabinet Sarah Nacass (Place Vendôme)",
        city: "Place Vendôme",
        address: "10 Place Vendôme, 75001 Paris",
        acuityAddress: "10 Place Vendôme, 75001 Paris. ",
        latitude: 48.86680536668918,
        longitude: 2.3298253641420548,
        accessMethods: "Métro - Pyramides (lignes M7 et M14) / Bus - Petits Champs - Danielle Casanova (lignes 21, 27, 29 68 et 95)",
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Île-de-France",
        path: "/fr/sarahnacass/ile-de-france",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["place-vendome", "75", "paris-1", "ile-de-france", "paris", "idf"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["ile-de-france"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0010",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Annecy)",
        city: "Annecy",
        address: "4 Rue Saint-François de Sales, 74000 Annecy",
        acuityAddress: "4 Rue Saint-François de Sales, 74000 Annecy. ",
        latitude: 45.90061530441029,
        longitude: 6.122596325510445,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Auvergne-Rhône-Alpes",
        path: "/fr/sarahnacass/auvergne-rhone-alpes",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["annecy", "74", "haute-savoie", "auvergne-rhone-alpes"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0011",
    },
    {
        pathId: 1, name: "Cabinet Sarah Nacass (Clermont-Ferrand)",
        city: "Clermont-Ferrand",
        address: "7 Rue Barillot Veuve Coupelon, 63000 Clermont-Ferrand",
        acuityAddress: "7 Rue Barillot Veuve Coupelon, 63000 Clermont-Ferrand. ",
        latitude: 45.76899278949666,
        longitude: 3.082090337463179,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Auvergne-Rhône-Alpes",
        path: "/fr/sarahnacass/auvergne-rhone-alpes",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["clermont-ferrand", "63", "puy-de-dome", "auvergne-rhone-alpes"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0012",
    },
    {
        pathId: 2, name: "Cabinet Sarah Nacass (Grenoble)",
        city: "Grenoble",
        address: "155-157 Cours Berriat, 38000 Grenoble",
        acuityAddress: "155-157 Cours Berriat, 38000 Grenoble. ",
        latitude: 45.18804422570645,
        longitude: 5.7045654580898395,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Auvergne-Rhône-Alpes",
        path: "/fr/sarahnacass/auvergne-rhone-alpes",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["grenoble", "38", "isere", "auvergne-rhone-alpes"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0013",
    },
    {
        pathId: 3, name: "Cabinet Sarah Nacass (Lyon)",
        city: "Lyon",
        address: "Immeuble Danica B, 21 Avenue Georges Pompidou, 69003 Lyon",
        acuityAddress: "Immeuble Danica B, 21 Avenue Georges Pompidou, 69003 Lyon. ",
        latitude: 45.75962383881251,
        longitude: 4.864725125501622,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Auvergne-Rhône-Alpes",
        path: "/fr/sarahnacass/auvergne-rhone-alpes",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["lyon", "69", "rhone", "auvergne-rhone-alpes"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0014",
    },
    {
        pathId: 4, name: "Cabinet Sarah Nacass (Valence)",
        city: "Valence",
        address: "Le Cube Numérique (Valence TGV), 8 Avenue de la Gare, 26300 Alixan",
        acuityAddress: "Le Cube Numérique (Valence TGV), 8 Avenue de la Gare, 26300 Alixan. ",
        latitude: 44.98721229978656,
        longitude: 4.975069184961377,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Auvergne-Rhône-Alpes",
        path: "/fr/sarahnacass/auvergne-rhone-alpes",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["valence", "26", "drome", "auvergne-rhone-alpes"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0015",
    },
    {
        pathId: 5, name: "Cabinet Sarah Nacass (Vichy)",
        city: "Vichy",
        address: "37 Avenue de Gramont, 03200 Vichy",
        acuityAddress: "37 Avenue de Gramont, 03200 Vichy. ",
        latitude: 46.1293355180952,
        longitude: 3.430810260494821,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Auvergne-Rhône-Alpes",
        path: "/fr/sarahnacass/auvergne-rhone-alpes",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["vichy", "03", "allier", "auvergne-rhone-alpes"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0016",
    },
    {
        pathId: 6, name: "Cabinet Sarah Nacass (Montélimar)",
        city: "Montélimar",
        address: "17 Avenue du Maréchal Juin, 26200 Montélimar",
        acuityAddress: "17 Avenue du Maréchal Juin, 26200 Montélimar. Se diriger vers les panneaux L'Effet Papillon Montélimar Coworking puis demander le bureau Sarah Nacass à l'accueil",
        latitude: 44.55910698528246,
        longitude: 4.757878467811926,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Auvergne-Rhône-Alpes",
        path: "/fr/sarahnacass/auvergne-rhone-alpes",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["montelimar", "03", "allier", "auvergne-rhone-alpes"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0017",
    },
    {
        pathId: 7, name: "Cabinet Sarah Nacass (Saint-Étienne)",
        city: "Saint-Étienne",
        address: "7 Rue Richelandière, 42000 Saint-Étienne",
        acuityAddress: "7 Rue Richelandière, 42000 Saint-Étienne. ",
        latitude: 45.43922148850106,
        longitude: 4.398434526903134,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Auvergne-Rhône-Alpes",
        path: "/fr/sarahnacass/auvergne-rhone-alpes",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["saint-etienne", "03", "allier", "auvergne-rhone-alpes"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0018",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Dijon)",
        city: "Dijon",
        address: "14 Rue Pierre de Coubertin, 21000 Dijon",
        acuityAddress: "14 Rue Pierre de Coubertin, 21000 Dijon. ",
        latitude: 47.31148294654205,
        longitude: 5.080204846148599,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Bourgogne-Franche-Comté",
        path: "/fr/sarahnacass/bourgogne-franche-comte",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["dijon", "21", "cote-d-or", "bourgogne-franche-comte"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0019",
    },
    {
        pathId: 1, name: "Cabinet Sarah Nacass (Besançon)",
        city: "Besançon",
        address: "4 Rue de la Préfecture, 25000 Besançon",
        acuityAddress: "4 Rue de la Préfecture, 25000 Besançon. ",
        latitude: 47.2359942647092,
        longitude: 6.025972198118561,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Bourgogne-Franche-Comté",
        path: "/fr/sarahnacass/bourgogne-franche-comte",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["besancon", "21", "cote-d-or", "bourgogne-franche-comte"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0020",
    },
    {
        pathId: 2, name: "Cabinet Sarah Nacass (Chalon-sur-Saône)",
        city: "Chalon-sur-Saône",
        address: "12 Rue de Thiard, 71100 Chalon-sur-Saône, France",
        acuityAddress: "12 Rue de Thiard, 71100 Chalon-sur-Saône, France. Se diriger vers les panneaux Bureaux My cowork, puis demander le bureau Sarah Nacass à l'accueil ",
        latitude: 46.78248559650737,
        longitude: 4.852822271163991,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Bourgogne-Franche-Comté",
        path: "/fr/sarahnacass/bourgogne-franche-comte",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["chalon-sur-saone", "71", "saone-et-loire", "bourgogne-franche-comte"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0021",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Rennes)",
        city: "Rennes",
        address: "Immeuble 3 Soleils, 20 Rue d'Isly, 35000 Rennes",
        acuityAddress: "Immeuble 3 Soleils, 20 Rue d'Isly, 35000 Rennes. ",
        latitude: 48.10556466967973,
        longitude: -1.6779310393783946,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Bretagne",
        path: "/fr/sarahnacass/bretagne",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["rennes", "35", "ille-et-vilaine", "bretagne"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0022",
    },
    {
        pathId: 1, name: "Cabinet Sarah Nacass (Vannes)",
        city: "Vannes",
        address: "1 Rue du Drezen, 56000 Vannes",
        acuityAddress: "1 Rue du Drezen, 56000 Vannes. ",
        latitude: 47.653806457826676,
        longitude: -2.7596917627767823,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Bretagne",
        path: "/fr/sarahnacass/bretagne",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["vannes", "56", "morbihan", "bretagne"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0023",
    },
    {
        pathId: 2, name: "Cabinet Sarah Nacass (Lorient)",
        city: "Lorient",
        address: "9 Cr de Chazelles, 56100 Lorient",
        acuityAddress: "9 Cr de Chazelles, 56100 Lorient. ",
        latitude: 47.755416585292416,
        longitude: -3.3639801603533996,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Bretagne",
        path: "/fr/sarahnacass/bretagne",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["lorient", "56", "morbihan", "bretagne"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0024",
    },
    {
        pathId: 3, name: "Cabinet Sarah Nacass (Brest)",
        city: "Brest",
        address: "Elo Business Center, 50 Rue Henry de Monfreid, 29200 Brest",
        acuityAddress: "Elo Business Center, 50 Rue Henry de Monfreid, 29200 Brest. ",
        latitude: 48.387200747669056,
        longitude: -4.4758296758273675,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Bretagne",
        path: "/fr/sarahnacass/bretagne",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["brest", "29", "finistere", "bretagne"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0025",
    },
    {
        pathId: 4, name: "Cabinet Sarah Nacass (Quimper)",
        city: "Quimper",
        address: "1 rue Aristide Briand",
        acuityAddress: "1 rue Aristide Briand. ",
        latitude: 47.99599953296781,
        longitude: -4.096897140998086,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Bretagne",
        path: "/fr/sarahnacass/bretagne",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["quimper", "29", "finistere", "bretagne"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0026",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Tours)",
        city: "Tours",
        address: "6 Rue d'Entraigues, 37000 Tours",
        acuityAddress: "6 Rue d'Entraigues, 37000 Tours. ",
        latitude: 47.388081429260154,
        longitude: 0.6891386214661178,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Centre-Val de Loire",
        path: "/fr/sarahnacass/centre-val-de-loire",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["tours", "37", "indre-et-loire", "centre-val-de-loire"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0027",
    },
    {
        pathId: 1, name: "Cabinet Sarah Nacass (Orléans)",
        city: "Orléans",
        address: "4 Pass. de la Râpe, 45000 Orléans",
        acuityAddress: "4 Pass. de la Râpe, 45000 Orléans. ",
        latitude: 47.91666430185205,
        longitude: 1.900362840466488,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Centre-Val de Loire",
        path: "/fr/sarahnacass/centre-val-de-loire",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["orleans", "37", "indre-et-loire", "centre-val-de-loire"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0028",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Mulhouse)",
        city: "Mulhouse",
        address: "La Tour de l'Europe, 3 Boulevard de l'Europe, 68100 Mulhouse",
        acuityAddress: "La Tour de l'Europe, 3 Boulevard de l'Europe, 68100 Mulhouse. ",
        latitude: 47.74988687200178,
        longitude: 7.340574033611785,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Grand Est",
        path: "/fr/sarahnacass/grand-est",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["mulhouse", "68", "haut-rhin", "grand-est"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0029",
    },
    {
        pathId: 1, name: "Cabinet Sarah Nacass (Nancy)",
        city: "Nancy",
        address: "3 Place Simone Veil, 54000 Nancy",
        acuityAddress: "3 Place Simone Veil, 54000 Nancy. ",
        latitude: 48.690344036737244,
        longitude: 6.1740094557499345,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Grand Est",
        path: "/fr/sarahnacass/grand-est",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["nancy", "54", "meurthe-et-moselle", "grand-est"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0030",
    },
    {
        pathId: 2, name: "Cabinet Sarah Nacass (Reims)",
        city: "Reims",
        address: "9-11 Rue Gaston Boyer, 51100 Reims",
        acuityAddress: "9-11 Rue Gaston Boyer, 51100 Reims. ",
        latitude: 49.26162177652715,
        longitude: 4.019899415268115,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Grand Est",
        path: "/fr/sarahnacass/grand-est",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["reims", "51", "marne", "grand-est"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0031",
    },
    {
        pathId: 3, name: "Cabinet Sarah Nacass (Strasbourg)",
        city: "Strasbourg",
        address: "20 Place des Halles, 67000 Strasbourg",
        acuityAddress: "20 Place des Halles, 67000 Strasbourg. ",
        latitude: 48.586778663546106,
        longitude: 7.741286447538362,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Grand Est",
        path: "/fr/sarahnacass/grand-est",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["strasbourg", "51", "bas-rhin", "grand-est"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0032",
    },
    {
        pathId: 4, name: "Cabinet Sarah Nacass (Metz)",
        city: "Metz",
        address: "19 Avenue Foch, 57000 Metz",
        acuityAddress: "19 Avenue Foch, 57000 Metz. ",
        latitude: 49.11152797705699,
        longitude: 6.17533993940842,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Grand Est",
        path: "/fr/sarahnacass/grand-est",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["metz", "51", "bas-rhin", "grand-est"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0033",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Amiens)",
        city: "Amiens",
        address: "47 Place Alphonse Fiquet, 80000 Amiens",
        acuityAddress: "47 Place Alphonse Fiquet, 80000 Amiens. ",
        latitude: 49.89077265782512,
        longitude: 2.3081009026315193,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Hauts-de-France",
        path: "/fr/sarahnacass/hauts-de-france",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["amiens", "80", "somme", "hauts-de-france"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0034",
    },
    {
        pathId: 1, name: "Cabinet Sarah Nacass (Beauvais)",
        city: "Beauvais",
        address: "L'atelier 1 rue du Pont de Paris, 60000 Beauvais",
        acuityAddress: "L'atelier 1 rue du Pont de Paris, 60000 Beauvais. ",
        latitude: 49.427640950810606,
        longitude: 2.0819993766510527,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Hauts-de-France",
        path: "/fr/sarahnacass/hauts-de-france",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["beauvais", "60", "oise", "hauts-de-france"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0035",
    },
    {
        pathId: 2, name: "Cabinet Sarah Nacass (Lille)",
        city: "Lille",
        address: "Gare de Lille Flandres Accès depuis le Hall principal, 1 Place de la Gare, 59000 Lille",
        acuityAddress: "Gare de Lille Flandres Accès depuis le Hall principal, 1 Place de la Gare, 59000 Lille. ",
        latitude: 50.63605554023047,
        longitude: 3.069951149973083,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Hauts-de-France",
        path: "/fr/sarahnacass/hauts-de-france",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["lille", "59", "nord", "hauts-de-france"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0036",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Saint-Paul (La Réunion))",
        city: "Saint-Paul (La Réunion)",
        address: "123 rue des sables Grand Fond, 97434 La Réunion",
        acuityAddress: "123 rue des sables Grand Fond, 97434 La Réunion. ",
        latitude: -21.0372728680726,
        longitude: 55.21771412248392,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Dom-Tom",
        path: "/fr/sarahnacass/dom-tom",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["saint-paul", "la-reunion"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["original"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 0,
        idLocation: "0037",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Caen)",
        city: "Caen",
        address: "Mai'be, 82 Boulevard Dunois, 14000 Caen",
        acuityAddress: "Mai'be, 82 Boulevard Dunois, 14000 Caen. ",
        latitude: 49.18489160170148,
        longitude: -0.3861604290910527,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Normandie",
        path: "/fr/sarahnacass/normandie",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["caen", "14", "calvados", "normandie"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0038",
    },
    {
        pathId: 1, name: "Cabinet Sarah Nacass (Rouen)",
        city: "Rouen",
        address: "7 bis Rue Jeanne d'Arc, 76100 Rouen",
        acuityAddress: "7 bis Rue Jeanne d'Arc, 76100 Rouen. ",
        latitude: 49.439568351996485,
        longitude: 1.0886296883207625,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Normandie",
        path: "/fr/sarahnacass/normandie",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["rouen", "76", "seine-maritime", "normandie"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0039",
    },
    {
        pathId: 2, name: "Cabinet Sarah Nacass (Le Havre)",
        city: "Le Havre",
        address: "85 Bd de Strasbourg, 76600 Le Havre",
        acuityAddress: "85 Bd de Strasbourg, 76600 Le Havre. ",
        latitude: 49.49348505326141,
        longitude: 0.11107937116399098,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Normandie",
        path: "/fr/sarahnacass/normandie",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["le-havre", "76", "seine-maritime", "normandie"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0040",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Bordeaux)",
        city: "Bordeaux",
        address: "Gare de Bordeaux Saint-Jean, Pavillon Nord, Rue Charles Domercq, 33800 Bordeaux",
        acuityAddress: "Gare de Bordeaux Saint-Jean, Pavillon Nord, Rue Charles Domercq, 33800 Bordeaux. ",
        latitude: 44.827194187099266,
        longitude: -0.556238656355062,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Nouvelle-Aquitaine",
        path: "/fr/sarahnacass/nouvelle-aquitaine",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["bordeaux", "33", "gironde", "nouvelle-aquitaine"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0041",
    },
    {
        pathId: 1, name: "Cabinet Sarah Nacass (Limoges)",
        city: "Limoges",
        address: "50 Boulevard Gambetta, 87000 Limoges",
        acuityAddress: "50 Boulevard Gambetta, 87000 Limoges. ",
        latitude: 45.828455115154576,
        longitude: 1.2565931960581296,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Nouvelle-Aquitaine",
        path: "/fr/sarahnacass/nouvelle-aquitaine",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["limoges", "87", "haute-vienne", "nouvelle-aquitaine"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0042",
    },
    {
        pathId: 2, name: "Cabinet Sarah Nacass (Niort)",
        city: "Niort",
        address: "12 Avenue Jacques Bujault, 79000 Niort",
        acuityAddress: "12 Avenue Jacques Bujault, 79000 Niort. ",
        latitude: 46.32200905023256,
        longitude: -0.4587010947030282,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Nouvelle-Aquitaine",
        path: "/fr/sarahnacass/nouvelle-aquitaine",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["niort", "79", "deux-sevres", "nouvelle-aquitaine"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0043",
    },
    {
        pathId: 3, name: "Cabinet Sarah Nacass (Saintes)",
        city: "Saintes",
        address: "18 Boulevard Guillet Maillet, 17100 Saintes",
        acuityAddress: "18 Boulevard Guillet Maillet, 17100 Saintes. ",
        latitude: 45.74810353408224,
        longitude: -0.6256491167335162,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Nouvelle-Aquitaine",
        path: "/fr/sarahnacass/nouvelle-aquitaine",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["saintes", "17", "charente-maritime", "nouvelle-aquitaine"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0044",
    },
    {
        pathId: 4, name: "Cabinet Sarah Nacass (La Rochelle)",
        city: "La Rochelle",
        address: "24 Rue du Bastion Saint-Nicolas, 17000 La Rochelle",
        acuityAddress: "24 Rue du Bastion Saint-Nicolas, 17000 La Rochelle. ",
        latitude: 46.15431567010348,
        longitude: -1.1459603832036798,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Nouvelle-Aquitaine",
        path: "/fr/sarahnacass/nouvelle-aquitaine",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["la-rochelle", "17", "charente-maritime", "nouvelle-aquitaine"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0045",
    },
    {
        pathId: 5, name: "Cabinet Sarah Nacass (Poitiers)",
        city: "Poitiers",
        address: "5 Rue Victor Hugo, 86000 Poitiers",
        acuityAddress: "5 Rue Victor Hugo, 86000 Poitiers. ",
        latitude: 46.580851759305105,
        longitude: 0.33769524039476795,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Nouvelle-Aquitaine",
        path: "/fr/sarahnacass/nouvelle-aquitaine",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["poitiers", "86", "vienne", "nouvelle-aquitaine"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0046",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Carcassonne)",
        city: "Carcassonne",
        address: "Coworking Agglo, 302 Rue Lamarck, 11000 Carcassonne",
        acuityAddress: "Coworking Agglo, 302 Rue Lamarck, 11000 Carcassonne. ",
        latitude: 43.213324349370446,
        longitude: 2.323576595898317,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Occitanie",
        path: "/fr/sarahnacass/occitanie",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["carcassonne", "11", "aude", "occitanie"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0047",
    },
    {
        pathId: 1, name: "Cabinet Sarah Nacass (Montpellier)",
        city: "Montpellier",
        address: "Espace Optimum, 450 Rue Baden Powell, 34000 Montpellier",
        acuityAddress: "Espace Optimum, 450 Rue Baden Powell, 34000 Montpellier. ",
        latitude: 43.610078471812045,
        longitude: 3.908221666474266,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Occitanie",
        path: "/fr/sarahnacass/occitanie",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["montpellier", "34", "herault", "occitanie"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0048",
    },
    {
        pathId: 2, name: "Cabinet Sarah Nacass (Narbonne)",
        city: "Narbonne",
        address: "12 boulevard Gambetta 11100 Narbonne",
        acuityAddress: "12 boulevard Gambetta 11100 Narbonne. Se diriger vers l'accueil puis demander le bureau Sarah Nacass ",
        latitude: 43.18235539253209,
        longitude: 3.007661695595673,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Occitanie",
        path: "/fr/sarahnacass/occitanie",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["narbonne", "11", "aude", "occitanie"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0049",
    },
    {
        pathId: 3, name: "Cabinet Sarah Nacass (Nîmes)",
        city: "Nîmes",
        address: "2 Rue de la Cité Foulc, 30000 Nîmes",
        acuityAddress: "2 Rue de la Cité Foulc, 30000 Nîmes. ",
        latitude: 43.83351113812346,
        longitude: 4.360100172279996,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Occitanie",
        path: "/fr/sarahnacass/occitanie",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["nimes", "30", "gard", "occitanie"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0050",
    },
    {
        pathId: 4, name: "Cabinet Sarah Nacass (Saint-Lizier)",
        city: "Saint-Lizier",
        address: "8 Rue Notre Dame, 09190 Saint-Lizier",
        acuityAddress: "8 Rue Notre Dame, 09190 Saint-Lizier. ",
        latitude: 43.00272995094061,
        longitude: 1.1364722857120717,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Occitanie",
        path: "/fr/sarahnacass/occitanie",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["saint-lizier", "09", "ariege", "occitanie"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0051",
    },
    {
        pathId: 5, name: "Cabinet Sarah Nacass (Sète)",
        city: "Sète",
        address: "3 bis Rue Gabriel Péri, 34200 Sète",
        acuityAddress: "3 bis Rue Gabriel Péri, 34200 Sète. Se diriger vers les panneaux La Palanquée puis demander le bureau Sarah Nacass à l'accueil",
        latitude: 43.40520246972213,
        longitude: 3.6958278199981445,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Occitanie",
        path: "/fr/sarahnacass/occitanie",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["sete", "34", "herault", "occitanie"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0052",
    },
    {
        pathId: 6, name: "Cabinet Sarah Nacass (Toulouse)",
        city: "Toulouse",
        address: "Le Pré Catelan, 78 Allée Jean Jaurès Bâtiment F, 31000 Toulouse",
        acuityAddress: "Le Pré Catelan, 78 Allée Jean Jaurès Bâtiment F, 31000 Toulouse. ",
        latitude: 43.60803228938993,
        longitude: 1.4531688457945602,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Occitanie",
        path: "/fr/sarahnacass/occitanie",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["toulouse", "31", "haute-garonne", "occitanie"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0053",
    },
    {
        pathId: 7, name: "Cabinet Sarah Nacass (Béziers )",
        city: "Béziers ",
        address: "6, rue Pierre FLOURENS  34500 Béziers",
        acuityAddress: "6, rue Pierre FLOURENS  34500 Béziers. Centre HOBSON  puis demander le bureau Sarah Nacass à l'accueil",
        latitude: 43.34336032690212,
        longitude: 3.2121292017082266,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Occitanie",
        path: "/fr/sarahnacass/occitanie",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["beziers", "34", "herault", "occitanie"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0054",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Angers)",
        city: "Angers",
        address: "19 Place du Président Kennedy, 49100 Angers",
        acuityAddress: "19 Place du Président Kennedy, 49100 Angers. ",
        latitude: 47.46882851082525,
        longitude: -0.5580431952906976,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Pays de la Loire",
        path: "/fr/sarahnacass/pays-de-la-loire",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["angers", "49", "maine-et-loire", "pays-de-la-loire"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 0,
        idLocation: "0055",
    },
    {
        pathId: 1, name: "Cabinet Sarah Nacass (La Chapelle sur Erdre)",
        city: "La Chapelle sur Erdre",
        address: "4 Rue du Devon, 44240 La Chapelle sur Erdre",
        acuityAddress: "4 Rue du Devon, 44240 La Chapelle sur Erdre. Se diriger vers les panneaux Le Totem hôtel Kalifornia - 2eme porte au fond du parking",
        latitude: 47.28067186778396,
        longitude: -1.5535935425052103,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Pays de la Loire",
        path: "/fr/sarahnacass/pays-de-la-loire",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["la-chapelle-sur-erdre", "44", "loire-atlantique", "pays-de-la-loire"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0056",
    },
    {
        pathId: 2, name: "Cabinet Sarah Nacass (Le Mans)",
        city: "Le Mans",
        address: "Place du 8 Mai 1945, 72000 Le Mans",
        acuityAddress: "Place du 8 Mai 1945, 72000 Le Mans. ",
        latitude: 47.99578495314063,
        longitude: 0.19212231399752216,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Pays de la Loire",
        path: "/fr/sarahnacass/pays-de-la-loire",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["le-mans", "72", "sarthe", "pays-de-la-loire"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 0,
        idLocation: "0057",
    },
    {
        pathId: 3, name: "Cabinet Sarah Nacass (Nantes)",
        city: "Nantes",
        address: "Nantes Euronantes Gare Immeuble Skyline, 22 Mail Pablo Picasso, 44000 Nantes",
        acuityAddress: "Nantes Euronantes Gare Immeuble Skyline, 22 Mail Pablo Picasso, 44000 Nantes. ",
        latitude: 47.21535902494571,
        longitude: -1.5367935761802358,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Pays de la Loire",
        path: "/fr/sarahnacass/pays-de-la-loire",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["nantes", "44", "loire-atlantique", "pays-de-la-loire"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0058",
    },
    {
        pathId: 4, name: "Cabinet Sarah Nacass (Saint-Nazaire)",
        city: "Saint-Nazaire",
        address: "76 Avenue de la République, 44600 Saint-Nazaire",
        acuityAddress: "76 Avenue de la République, 44600 Saint-Nazaire. ",
        latitude: 47.281193416117944,
        longitude: -2.2114890288360094,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Pays de la Loire",
        path: "/fr/sarahnacass/pays-de-la-loire",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["saint-nazaire", "44", "loire-atlantique", "pays-de-la-loire"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["nord-ouest"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0059",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Aix en Provence - Centre)",
        city: "Aix en Provence - Centre",
        address: "5 Rue des Allumettes, 13100 Aix-en-Provence",
        acuityAddress: "5 Rue des Allumettes, 13100 Aix-en-Provence. ",
        latitude: 43.524487197073604,
        longitude: 5.440070659379183,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Provence-Alpes-Côte d'Azur",
        path: "/fr/sarahnacass/provence-alpes-cote-d-azur",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["aix-en-provence", "13", "bouches-du-rhone", "provence-alpes-cote-d-azur"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 0,
        idLocation: "0060",
    },
    {
        pathId: 1, name: "Cabinet Sarah Nacass (Aix en Provence - Gare TGV)",
        city: "Aix en Provence - Gare TGV",
        address: "31 Parc du Golf, 13593 Aix-en-Provence",
        acuityAddress: "31 Parc du Golf, 13593 Aix-en-Provence. ",
        latitude: 43.481205930775126,
        longitude: 5.3650023805720775,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Provence-Alpes-Côte d'Azur",
        path: "/fr/sarahnacass/provence-alpes-cote-d-azur",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["aix-en-provence", "13", "bouches-du-rhone", "provence-alpes-cote-d-azur"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0061",
    },
    {
        pathId: 2, name: "Cabinet Sarah Nacass (Arles)",
        city: "Arles",
        address: "29 Rue des Arènes, 13200 Arles",
        acuityAddress: "29 Rue des Arènes, 13200 Arles. ",
        latitude: 43.677713203134644,
        longitude: 4.628791554821665,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Provence-Alpes-Côte d'Azur",
        path: "/fr/sarahnacass/provence-alpes-cote-d-azur",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["arles", "13", "bouches-du-rhone", "provence-alpes-cote-d-azur"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0062",
    },
    {
        pathId: 3, name: "Cabinet Sarah Nacass (Marseille)",
        city: "Marseille",
        address: "Les Docks, 10 Place de la Joliette, Atrium 10.6, 13002 Marseille",
        acuityAddress: "Les Docks, 10 Place de la Joliette, Atrium 10.6, 13002 Marseille. ",
        latitude: 43.305393899345454,
        longitude: 5.366006225351594,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Provence-Alpes-Côte d'Azur",
        path: "/fr/sarahnacass/provence-alpes-cote-d-azur",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["marseille", "13", "bouches-du-rhone", "provence-alpes-cote-d-azur"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0063",
    },
    {
        pathId: 4, name: "Cabinet Sarah Nacass (Nice)",
        city: "Nice",
        address: "81 Rue de France, 3ème étage, 06000 Nice",
        acuityAddress: "81 Rue de France, 3ème étage, 06000 Nice. ",
        latitude: 43.69531445325955,
        longitude: 7.25716110635938,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Provence-Alpes-Côte d'Azur",
        path: "/fr/sarahnacass/provence-alpes-cote-d-azur",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["nice", "06", "alpes-maritimes", "provence-alpes-cote-d-azur"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0064",
    },
    {
        pathId: 5, name: "Cabinet Sarah Nacass (Avignon)",
        city: "Avignon",
        address: "40 Boulevard Limbert, 84000 Avignon",
        acuityAddress: "40 Boulevard Limbert, 84000 Avignon. ",
        latitude: 43.94995610400062,
        longitude: 4.819880642329818,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Provence-Alpes-Côte d'Azur",
        path: "/fr/sarahnacass/provence-alpes-cote-d-azur",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["Avignon", "06", "alpes-maritimes", "provence-alpes-cote-d-azur"],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-est"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0065",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Brussels)",
        city: "Brussels",
        address: "Avenue Fonsny 46 box 59, 1060 Brussels",
        acuityAddress: "Avenue Fonsny 46 box 59, 1060 Brussels. ",
        latitude: 50.835759941742104,
        longitude: 4.333679455281669,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Brussels",
        path: "/be/sarahnacass/belgique?sID=0",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["belgium", "belgique", "europe", "brussels", "bruxelles"],
        country: {code: "be", name: "Belgique"},
        phone: {number: phones["original"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0066",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Genève)",
        city: "Genève",
        address: "Rue du Commerce 4, 1204 Genève",
        acuityAddress: "Rue du Commerce 4, 1204 Genève. ",
        latitude: 46.20415968761677,
        longitude: 6.1448115790140365,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Genève",
        path: "/ch/sarahnacass/suisse?sID=0",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["geneve", "switzerland", "bale", "europe", "suisse"],
        country: {code: "ch", name: "Suisse"},
        phone: {number: phones["original"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0067",
    },
    {
        pathId: 1, name: "Cabinet Sarah Nacass (Lausanne)",
        city: "Lausanne",
        address: "Voie du Chariot 3/4th floor, 1003 Lausanne",
        acuityAddress: "Voie du Chariot 3/4th floor, 1003 Lausanne. ",
        latitude: 46.52081375721933,
        longitude: 6.629500274720877,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Lausanne",
        path: "/ch/sarahnacass/suisse?sID=1",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["lausanne", "switzerland", "bale", "europe", "suisse"],
        country: {code: "ch", name: "Suisse"},
        phone: {number: phones["original"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0068",
    },
    {
        pathId: 2, name: "Cabinet Sarah Nacass (Berne)",
        city: "Berne",
        address: "Schanzenstrasse 4a, 3008 Bern, Suisse",
        acuityAddress: "Schanzenstrasse 4a, 3008 Bern, Suisse. ",
        latitude: 46.948561679612666,
        longitude: 7.437406363497682,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Berne",
        path: "/ch/sarahnacass/suisse?sID=2",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["berne", "switzerland", "europe", "suisse"],
        country: {code: "ch", name: "Suisse"},
        phone: {number: phones["original"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 0,
        idLocation: "0069",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Monaco)",
        city: "Monaco",
        address: "L'Albu, 17 Avenue Albert II 98000 Monaco",
        acuityAddress: "L'Albu, 17 Avenue Albert II 98000 Monaco. ",
        latitude: 43.729701902803974,
        longitude:  7.415645488236724,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Monaco",
        path: "/mc/sarahnacass/monaco?sID=0",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: [],
        country: {code: "mc", name: "Monaco"},
        phone: {number: phones["original"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0070",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Luxembourg)",
        city: "Luxembourg",
        address: "26 Boulevard Royal, Level 5, 2449 Luxembourg",
        acuityAddress: "26 Boulevard Royal, Level 5, 2449 Luxembourg. ",
        latitude: 49.61122862296595,
        longitude: 6.125568813788473,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052485,
        appointmentTypeIdNotPaid: 67052492,
        calendarId: {
            0: praticiens["cabinet_sarahnacass"]["calendar"],
        },
        geoZoneName: "Luxembourg",
        path: "/lu/sarahnacass/luxembourg?sID=0",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["luxembourg", "luxembourg city", "luxembourg ville"],
        country: {code: "lu", name: "Luxembourg"},
        phone: {number: phones["original"]},
        tarif: tarifs["union-europeenne"],
        acuityAPI: 1,
        available: 1,
        idLocation: "0071",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Québec)",
        city: "Québec",
        address: "1020 Rue Bouvier, QC G2K 0H3 Québec",
        acuityAddress: "1020 Rue Bouvier, QC G2K 0H3 Québec. Se diriger vers les panneaux Regus / Stop & Work puis demander le bureau Sarah Nacass à l'accueil",
        latitude: 46.77032727564767,
        longitude: -71.28913910809703,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67053684,
        appointmentTypeIdNotPaid: 67053689,
        calendarId: {
            0: praticiens["cabinet_sarahnacass_2"]["calendar"],
        },
        geoZoneName: "Québec",
        path: "/ca/sarahnacass/canada?sID=0",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["quebec", "canada", "north america", "america", "amérique"],
        country: {code: "ca", name: "Canada"},
        phone: {number: phones["original"]},
        tarif: tarifs["canada"],
        acuityAPI: 2,
        available: 1,
        idLocation: "0072",
    },
    {
        pathId: 1, name: "Cabinet Sarah Nacass (Montréal)",
        city: "Montréal",
        address: "1200 McGill College Avenue Suite #1100, Montréal",
        acuityAddress: "1200 McGill College Avenue Suite #1100, Montréal. Se diriger vers les panneaux Regus / Stop & Work puis demander le bureau Sarah Nacass à l'accueil",
        latitude: 45.50131599202946,
        longitude: -73.57068544629118,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67053684,
        appointmentTypeIdNotPaid: 67053689,
        calendarId: {
            0: praticiens["cabinet_sarahnacass_2"]["calendar"],
        },
        geoZoneName: "Montréal",
        path: "/ca/sarahnacass/canada?sID=1",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["montreal", "canada", "north america", "america", "amérique"],
        country: {code: "ca", name: "Canada"},
        phone: {number: phones["original"]},
        tarif: tarifs["canada"],
        acuityAPI: 2,
        available: 1,
        idLocation: "0073",
    },
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Casablanca)",
        city: "Casablanca",
        address: "Crystal Building 1, 10th Floor, 20000 Casablanca",
        acuityAddress: "Crystal Building 1, 10th Floor, 20000 Casablanca. ",
        latitude: 33.60226895483137,
        longitude: -7.6176648903917625,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67053684,
        appointmentTypeIdNotPaid: 67053689,
        calendarId: {
            0: praticiens["cabinet_sarahnacass_2"]["calendar"],
        },
        geoZoneName: "Casablanca",
        path: "/ma/sarahnacass/maroc?sID=0",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["casablanca", "maroc", "afrique", "dar el beida", "darbia"],
        country: {code: "ma", name: "Maroc"},
        phone: {number: phones["original"]},
        tarif: tarifs["maroc"],
        acuityAPI: 2,
        available: 1,
        idLocation: "0074",
    },
    {
        pathId: 1, name: "Cabinet Sarah Nacass (Rabat)",
        city: "Rabat",
        address: "Immeuble Mahaj Ryad Center Bureaux, 5th floor, Building 7, 10100 Rabat",
        acuityAddress: "Immeuble Mahaj Ryad Center Bureaux, 5th floor, Building 7, 10100 Rabat. ",
        latitude: 33.96489586569456,
        longitude: -6.8677178685248474,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67053684,
        appointmentTypeIdNotPaid: 67053689,
        calendarId: {
            0: praticiens["cabinet_sarahnacass_2"]["calendar"],
        },
        geoZoneName: "Rabat",
        path: "/ma/sarahnacass/maroc?sID=1",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["rabat", "maroc", "afrique", "rabat-sale-zemmour-zaer"],
        country: {code: "ma", name: "Maroc"},
        phone: {number: phones["original"]},
        tarif: tarifs["maroc"],
        acuityAPI: 2,
        available: 1,
        idLocation: "0075",
    },
    {
        pathId: 2, name: "Cabinet Sarah Nacass (Tanger)",
        city: "Tanger",
        address: "IBN Batouta Mall, Avenue Youssef Ben Tachfine, 90013 Tangier, (شارع يوسف بن تاشفين، طنجة)",
        acuityAddress: "IBN Batouta Mall, Avenue Youssef Ben Tachfine, 90013 Tangier, (شارع يوسف بن تاشفين، طنجة). ",
        latitude: 35.7773155102371,
        longitude: -5.802054571991763,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67053684,
        appointmentTypeIdNotPaid: 67053689,
        calendarId: {
            0: praticiens["cabinet_sarahnacass_2"]["calendar"],
        },
        geoZoneName: "Tanger",
        path: "/ma/sarahnacass/maroc?sID=2",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: ["tanger", "maroc", "afrique", "tanger-tétouan-al hoceima"],
        country: {code: "ma", name: "Maroc"},
        phone: {number: phones["original"]},
        tarif: tarifs["maroc"],
        acuityAPI: 2,
        available: 1,
        idLocation: "0076",
    },
];


const residentiel = [
    {
        pathId: 0, name: "Cabinet Sarah Nacass (Montpellier / Sète)",
        city: "Montpellier / Sète",
        address: "Mas des Pins d'Argelliès, Chemin des justices, 34110 Frontignan",
        acuityAddress: "https://us02web.zoom.us/j/89415032352?pwd=Rlp2dDU1ODhGektNZ01MRlg4UCs2Zz09",
        latitude: 43.46665197505512,
        longitude: 3.7630112933874873,
        accessMethods: null,
        parkingAccess: null,
        othersInfos: "Accessible uniquement sur rendez-vous",
        appointmentTypeIdPaid: 67052510,
        calendarId: {
            0: praticiens["residentiel_sarahnacass"]["calendar"],
        },
        geoZoneName: "Montpellier / Sète",
        path: "/fr/residentiel?sID=0",
        weekEndAvailability: false,
        imageUri: null,
        advancedKeywords: [],
        country: {code: "fr", name: "France"},
        phone: {number: phones["sud-ouest"]},
        acuityAPI: 1,
        available: 1,
        idLocation: "0077",
    },
];
export { countriesDepthOfCoverage, locations, residentiel };

